Adding the support tracing of child models invoked from a BLS model
triton-inference-server/core pull request #234
Opened 2023-07-14 23:31 UTC by oandreeva-nv

Partially based on this PR: https://github.com/triton-inference-server/core/pull/172

2023-07-17 22:20 UTC, GuanLuo commented on include/triton/core/tritonbackend.h
> +/// If tracing is disabled, then `nullptr` will be returned.
```suggestion
/// If the request is not being traced, then `nullptr` will be returned.
```
Tracing can be configured to sample 1 for every few requests.

2023-07-17 22:20 UTC, GuanLuo commented on include/triton/core/tritonserver.h
> +/// \param child_trace Returns the child trace, spawned from the trace.
Mention caller owns the returned object and must release unless being transferred through other APIs (i.e. `TRITONSERVER_ServerInferAsync`)

2023-07-17 22:20 UTC, GuanLuo commented on src/tritonserver.cc
> +  tc::InferenceTrace* ltrace = reinterpret_cast<tc::InferenceTrace*>(trace);
check if `nullptr` first?

2023-07-21 00:41 UTC, GuanLuo submitted a review, later dismissed

2023-07-21 20:43 UTC, Tabrizian approved these changes

2023-07-26 19:28 UTC, rmccorm4 commented on include/triton/core/tritonbackend.h
> +#define TRITONBACKEND_API_VERSION_MINOR 14
This will have to be 15 because of my PR: https://github.com/triton-inference-server/core/pull/235

2023-07-26 19:32 UTC, rmccorm4 requested changes
LGTM, just backend API version bump

2023-07-27 20:09 UTC, rmccorm4 approved these changes

2023-08-02 18:56 UTC, tanmayv25 approved these changes

2023-08-07 21:57 UTC, merged