Change the default value for strict model config for parity with Server
triton-inference-server/core pull request #347
Opened 2024-05-01 17:01 UTC by Tabrizian

Auto-complete is enabled by default on the server side while it was disabled on the Python API because of this default value.

2024-05-01 21:51 UTC, rmccorm4 reviewed
LGTM - I was looking for this change too, but will leave approval to Neelay

2024-05-02 11:27 UTC, nnshah1 commented
I'm a little conflicted on the best approach here. During the initial implementation the goal was to be consistent with the C in process api and honor the defaults as set in the code. This value for strict model config was taken from:

https://github.com/triton-inference-server/core/blob/5fc928af68082896d49e385c49c478e76088532d/src/server.cc#L104 

That being said we can adopt the defaults as set by the server application as an alternative - however we also are now recommending users to set strict_model_config to True unless needed for their use case (opt-in instead of opt-out):

https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/deploy.html#disable-auto-complete-config-default-enabled 

let's discuss as part of python in process api productization epic (i.e. revisit default values)

2024-05-02 11:32 UTC, nnshah1 requested changes
pending discussion

2024-05-02 14:29 UTC, Tabrizian commented
> however we also are now recommending users to set strict_model_config to True unless needed for their use case (opt-in instead of opt-out):

https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/deploy.html#disable-auto-complete-config-default-enabled

Can you elaborate about the security risk of auto-complete?

2024-05-02 21:52 UTC, nnshah1 commented
> > however we also are now recommending users to set strict_model_config to True unless needed for their use case (opt-in instead of opt-out):
> 
> https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/deploy.html#disable-auto-complete-config-default-enabled
> 
> Can you elaborate about the security risk of auto-complete?

auto complete can more easily lead to non obvious results - since we offer the option to disable and it is not a necessary requirement for many use cases - the default for the server application likely should be to disable as basic principle of least priviledge / least feature - and make the team deploying the application responsible to enabling it.

2024-05-02 21:54 UTC, nnshah1 reviewed
In offline discussion we have added a separate task to review the default options for the in process APIs (so they all are consistent) and for the server application seperately. Unblocking this request in the mean time with the understanding that the default may change in the future after review.

2024-05-02 21:55 UTC, nnshah1 approved these changes

2024-05-03 05:50 UTC, rmccorm4 approved these changes
My $0.02 for the future discussion, maybe the python "high-level" wrapper can be a little more opinionated than the 1:1 bindings below it for ergonomics where we deem fit. 

As another data point for "prior art", we have a C++ high level wrapper around the C API, and it looks like it also has strict model config as `false` by default:
- https://github.com/triton-inference-server/developer_tools/blob/3d71fca07dfa7c68ef574566c809775bcf0312b6/server/src/server_wrapper.cc#L800
- https://github.com/triton-inference-server/developer_tools/blob/3d71fca07dfa7c68ef574566c809775bcf0312b6/server/src/server_wrapper.cc#L1539-L1540

Maybe the productization discussion could consider making the "high level wrappers" match rather than making 1:1 C-API match.

2024-05-03 14:47 UTC, Tabrizian commented
@nnshah1 @rmccorm4 I think we're all mostly on the same page. I agree with being more permissive in the API and restrictive in the `tritonserver` binary. Ideally, we need to ensure similar user-experience across all these different APIs. Thanks for the feedback and discussions.

2024-05-03 14:47 UTC, merged