Add validation for response cache + decoupled mode in parsing model config
triton-inference-server/core pull request #91
Opened 2022-07-01 00:00 UTC by rmccorm4

2022-07-01 18:55 UTC, nv-kmcgill53 commented on src/model_config_utils.cc
> +            "does not currently support decoupled model transaction policy. "
please change to " does not currently support _the_ decoupled model transaction policy. "

2022-07-01 19:08 UTC, nv-kmcgill53 submitted a review, later dismissed

2022-07-01 21:53 UTC, tanmayv25 requested changes

2022-07-01 21:53 UTC, tanmayv25 commented on src/model_config_utils.cc
> +        "Invalid combination for model " + config.name() +
```suggestion
        "Response Cache does not currently support model " + config.name() +
        " with 'decoupled' transaction policy. Please disable the response cache.");
```

2022-07-05 21:33 UTC, tanmayv25 approved these changes

2022-07-08 18:49 UTC, merged